apiVersion: v1
kind: Service
metadata:
  name: wp01-mysql
  labels:
    app: wp01
spec:
  ports:
    - name: 'port-3306'
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: wp01
    tier: mysql
  clusterIP: None