apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp01
  labels:
    app: wp01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp01
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp01
        tier: frontend
    spec:
      nodeSelector:
        tier: ux
        environment: dev
        instance-type: spot
      containers:
      - image: wordpress
        name: wp01
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: WORDPRESS_DB_HOST
          value: 'wp01-mysql'
        - name: WORDPRESS_DB_USER
          value: 'root'
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp01.mysql.secret
              key: password
        - name: WORDPRESS_DB_NAME
          value: 'wordpress01'
        - name: WORDPRESS_TABLE_PREFIX
          value: 'wp01_'
        - name: WORDPRESS_DEBUG
          value: '1'
        ports:
        - containerPort: 80
          protocol: TCP
          name: 'port-80'
        volumeMounts:
        - name: wp01-www
          mountPath: /var/www
        - name: wp01-cache
          mountPath: /var/cache
      volumes:
      - name: wp01-www
        persistentVolumeClaim:
          claimName: wp01.wordpress.pvc
      - name: wp01-cache
        persistentVolumeClaim:
          claimName: wp01.cache.pvc