apiVersion: v1
kind: Service
metadata:
  name: ps01
  labels:
    app: ps01
spec:
  ports:
    - name: 'port-80'
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: ps01
    tier: frontend
  type: NodePort
