apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps01.system.pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: 'standard'
  labels:
    app: ps01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps01.cache.pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: 'standard'
  labels:
    app: ps01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
