apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp02.mysql.pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: 'standard'
  labels:
    app: wp02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
