apiVersion: v1
kind: Service
metadata:
  name: wp02
  labels:
    app: wp02
spec:
  ports:
    - name: 'port-80'
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: wp02
    tier: frontend
  type: NodePort