apiVersion: v1
kind: Service
metadata:
  name: wp01
  labels:
    app: wp01
spec:
  ports:
    - name: 'port-80'
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: wp01
    tier: frontend
  type: NodePort
