apiVersion: v1
kind: Service
metadata:
  name: ps01-mysql
  labels:
    app: ps01
spec:
  ports:
    - name: 'port-3306'
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: ps01
    tier: mysql
  clusterIP: None
