kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ps01
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
mountOptions:
  - debug
